import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { run, tree } from '../upstream/workflow.mjs';
const root = fileURLToPath(new URL('../..', import.meta.url));
test('public-AST normalization is idempotent and retains constructor-before-location evaluation', t => {
    const stage = mkdtempSync(join(tmpdir(), 'jint-normalizer-')); t.after(() => rmSync(stage, { recursive: true, force: true }));
    const source = `class Parser {
    object Parse() => FinishNode(start, new BinaryExpression(ParseLeft(), ParseRight()));
    object Pick() => FinishNode(start, test ? new One(Read()) : new Two(Read()));
    object Switch() => FinishNode(start, token switch { 1 => new One(Read()), /* keep comma comment */ _ => new Two(Read()) });
    object Copy() => ReinterpretNode(original, new One(Read()));
    object End() => FinishNodeAt(start, end, new One(Read()));
    object Deferred() => FinishNode(start, constructedElsewhere);
    object Existing() => FinishNode(start, new One() { Range = CustomRange(), Location = CustomLocation() });
    object List() => NodeList.From(ref builder);
    object Single() => new NodeList<Node>(id);
    object OwnedArray() => new NodeList<Node>(array, count);
    object Range() => new Range(1, 2);
    object Position() => new Position(1, 2);
    object Location() => new SourceLocation(start, end, file);
    object TemplateValue() => new TemplateValue(cooked, raw);
    object ReadRange() => original._range;
}`;
    writeFileSync(join(stage, 'Parser.cs'), source);
    run('dotnet', ['build', 'eng/AdaptAst', '-c', 'Release'], root);
    const dll = join(root, 'eng/AdaptAst/bin/Release/net10.0/AdaptAst.dll');
    run('dotnet', [dll, stage], root);
    const result = readFileSync(join(stage, 'Parser.cs'), 'utf8');
    assert.match(result, /new BinaryExpression\(ParseLeft\(\), ParseRight\(\)\) \{ Range = NodeRange\(start\), Location = NodeLocation\(start\) \}/u);
    assert.match(result, /original.Range, Location = original.Location/u);
    assert.match(result, /Range = NodeRange\(start, end\)/u);
    assert.match(result, /Range = CustomRange\(\), Location = CustomLocation\(\)/u);
    assert.match(result, /FinishNode\(start, constructedElsewhere\)/u);
    assert.match(result, /Acornima.TemplateValue.From\(cooked, raw\)/u);
    assert.match(result, /ParserNodeList.From\(ref builder\)/u);
    assert.match(result, /NodeList.From<Node>\(id\)/u);
    assert.match(result, /new NodeList<Node>\(array, count\)/u);
    assert.ok(result.includes('/* keep comma comment */'));
    for (const name of ['Range', 'Position', 'SourceLocation']) assert.ok(result.includes(`${name}.From(`));
    assert.equal((result.match(/new (One|Two)\(Read\(\)\) \{ Range/gmu) ?? []).length, 6);
    const first = tree(stage); run('dotnet', [dll, stage], root); assert.deepEqual(tree(stage), first);
    writeFileSync(join(stage, 'Parser.cs'), 'class {');
    assert.throws(() => run('dotnet', [dll, stage], root), /Cannot normalize invalid C#/);
});

test('skill installation is repeatable and refuses to overwrite edited instructions', t => {
    const stage = mkdtempSync(join(tmpdir(), 'jint-skill-')); t.after(() => rmSync(stage, { recursive: true, force: true }));
    const install = join(root, 'eng/install-update-skill.mjs');
    run(process.execPath, [install, stage], root);
    run(process.execPath, [join(root, 'eng/validate-update-skill.mjs'), join(stage, 'jint-update-acornima')], root);
    const first = tree(stage); run(process.execPath, [install, stage], root); assert.deepEqual(tree(stage), first);
    writeFileSync(join(stage, 'jint-update-acornima/SKILL.md'), 'user customization');
    assert.throws(() => run(process.execPath, [install, stage], root), /Existing skill differs/);
    assert.equal(readFileSync(join(stage, 'jint-update-acornima/SKILL.md'), 'utf8'), 'user customization');
});
