import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, resolve } from 'node:path';
import { filesUnder, readSource } from './parser-files.mjs';

const usage = 'Usage: node eng/import-parser.mjs UPSTREAM_CHECKOUT GENERATED_SOURCES OUTPUT_DIR';
const args = process.argv.slice(2);
if (args.length !== 3 || args.includes('--help')) {
    console.log(usage);
    process.exit(args.includes('--help') ? 0 : 1);
}

const source = resolve(args[0], 'src/Acornima');
const generated = resolve(args[1], 'Acornima.SourceGenerators/Acornima.SourceGenerators.StringMatcherGenerator');
const target = resolve(args[2]);
if (existsSync(target) && readdirSync(target).length !== 0)
    throw new Error('Import output must be a new or empty directory');
const shared = new Set(['Operator', 'TokenKind', 'TemplateValue', 'Range', 'Position', 'SourceLocation',
    'SourceType', 'EcmaVersion', 'ExperimentalESFeatures']);
const excluded = new Set([...shared, 'AstVisitor', 'AstRewriter', 'AutoGeneratedAstVisitorAttribute', 'AssemblyInfo']);

function convert(text) {
    return text.replaceAll('Acornima', 'Jint.TypeScript.Parsing')
        .replaceAll('Jint.TypeScript.Parsing.Ast', 'Acornima.Ast')
        .replace(/^public ((?:(?:sealed|abstract|readonly|partial|ref|static) )*(?:class|struct|interface|enum|record|delegate)\b)/gmu, 'internal $1');
}

// Read all inputs before writing; an invalid checkout/generated path leaves output untouched.
const outputs = new Map();
for (const name of filesUnder(source, new Set(['Ast', 'bin', 'obj']))) {
    const extension = extname(name);
    if (!['.cs', '.resx'].includes(extension) || excluded.has(basename(name, extension))) continue;
    outputs.set(name, convert(readSource(join(source, name))));
}
for (const name of ['Parser', 'Tokenizer', 'TokenType']) {
    outputs.set(`${name}.Matchers.g.cs`, convert(readSource(join(generated, `Acornima.${name}.g.cs`))));
}
outputs.set('PublicTypes.cs', '// Shared value types belong to the official Acornima assembly.\n'
    + [...shared].sort().map(name => `global using ${name} = Acornima.${name};`).join('\n') + '\n');

for (const [name, text] of outputs) {
    const output = join(target, name);
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, text);
}
console.log(`Imported ${outputs.size} parser files into ${target}`);
